export const config = {
  apiKey: import.meta.env.VITE_TMDB_API_KEY,
  apiURL: 'https://api.themoviedb.org/3',
  imgBaseURL: 'http://image.tmdb.org/t/p',
  lang: 'es-ES',
  monthNames: [
    'Enero',
    'Febrero',
    'Marzo',
    'Abril',
    'Mayo',
    'Junio',
    'Julio',
    'Agosto',
    'Septiembre',
    'Octubre',
    'Noviembre',
    'Diciembre',
  ],
}
